[global]
daemonize = no
process_control_timeout = 20

[www]
listen = /var/run/php/php-fpm.sock
listen.mode = 0666
ping.path = /ping
access.suppress_path[] = /ping

php_admin_value[upload_max_filesize] = ${CLIENT_BODY_SIZE}
php_admin_value[post_max_size] = ${CLIENT_BODY_SIZE}
