<?php

use App\Entity\Data\Analysis;
use App\Entity\Data\ArchaeologicalSite;
use App\Entity\Data\Botany\Charcoal;
use App\Entity\Data\Botany\Seed;
use App\Entity\Data\Context;
use App\Entity\Data\History\Animal;
use App\Entity\Data\History\Plant;
use App\Entity\Data\History\WrittenSource;
use App\Entity\Data\History\WrittenSourceCitedWork;
use App\Entity\Data\Individual;
use App\Entity\Data\Join\Analysis\AnalysisBotanyCharcoal;
use App\Entity\Data\Join\Analysis\AnalysisBotanySeed;
use App\Entity\Data\Join\Analysis\AnalysisContextBotany;
use App\Entity\Data\Join\Analysis\AnalysisContextZoo;
use App\Entity\Data\Join\Analysis\AnalysisIndividual;
use App\Entity\Data\Join\Analysis\AnalysisPottery;
use App\Entity\Data\Join\Analysis\AnalysisSample;
use App\Entity\Data\Join\Analysis\AnalysisSampleBotany;
use App\Entity\Data\Join\Analysis\AnalysisSampleMicrostratigraphy;
use App\Entity\Data\Join\Analysis\AnalysisSedimentCoreDepth;
use App\Entity\Data\Join\Analysis\AnalysisSedimentCoreDepthBotany;
use App\Entity\Data\Join\Analysis\AnalysisSiteAnthropology;
use App\Entity\Data\Join\Analysis\AnalysisZooBone;
use App\Entity\Data\Join\Analysis\AnalysisZooTooth;
use App\Entity\Data\Join\ContextStratigraphicUnit;
use App\Entity\Data\Join\SampleStratigraphicUnit;
use App\Entity\Data\Join\SedimentCoreDepth;
use App\Entity\Data\MicrostratigraphicUnit;
use App\Entity\Data\PaleoclimateSample;
use App\Entity\Data\PaleoclimateSamplingSite;
use App\Entity\Data\Pottery;
use App\Entity\Data\Sample;
use App\Entity\Data\SamplingSite;
use App\Entity\Data\SamplingStratigraphicUnit;
use App\Entity\Data\SedimentCore;
use App\Entity\Data\StratigraphicUnit;
use App\Entity\Data\View\AbsDatingAnalysisView;
use App\Entity\Data\Zoo\Bone;
use App\Entity\Data\Zoo\Tooth;

return [
    Analysis::class => [
        'id' => 'Id',
        'identifier' => 'Identifier',
        'status' => 'Status',
        'type.code' => 'Type Code',
        'type.group' => 'Type Group',
        'type.value' => 'Type',
        'responsible' => 'Responsible',
        'year' => 'Year',
        'laboratory' => 'Laboratory',
        'summary' => 'Summary',
        'code' => 'Code',
    ],
    ArchaeologicalSite::class => [
        'id' => 'Id',
        'code' => 'Code',
        'name' => 'Name',
        'description' => 'Description',
        'chronologyLower' => 'Chronology Lower',
        'chronologyUpper' => 'Chronology Upper',
        'fieldDirector' => 'Field Director',
        'region.value' => 'Region',
        'n' => 'N',
        'e' => 'E',
    ],
    Charcoal::class => [
        'flat.value' => 'Flat ',
        'stratigraphicUnit.site.code' => 'Stratigraphic Unit Site Code',
        'stratigraphicUnit.site.name' => 'Stratigraphic Unit Site Name',
        'stratigraphicUnit.code' => 'Stratigraphic Unit Code',
        'taxonomy.value' => 'Taxonomy',
        'taxonomy.flat.value' => 'Taxonomy Flat',
        'taxonomy.flat.level' => 'Taxonomy Flat Level',
        'taxonomy.flat.rank' => 'Taxonomy Flat Rank',
        'taxonomy.flat.species' => 'Taxonomy Flat Species',
        'taxonomy.flat.genus' => 'Taxonomy Flat Genus',
        'taxonomy.flat.family' => 'Taxonomy Flat Family',
        'taxonomy.flat.class' => 'Taxonomy Flat Class',
        'taxonomy.flat.spanishName' => 'Taxonomy Flat Spanish Name',
        'taxonomy.flat.englishName' => 'Taxonomy Flat English Name',
        'taxonomy.flat.genusId' => 'Taxonomy Flat Genus Id',
        'taxonomy.flat.familyId' => 'Taxonomy Flat Family Id',
        'taxonomy.flat.classId' => 'Taxonomy Flat Class Id',
        'part.value' => 'Part',
        'cf' => 'Cf',
        'sp' => 'Sp',
        'type' => 'Type',
        'notes' => 'Notes',
    ],
    Seed::class => [
        'flat.value' => 'Flat',
        'stratigraphicUnit.site.code' => 'Stratigraphic Unit Site Code',
        'stratigraphicUnit.site.name' => 'Stratigraphic Unit Site Name',
        'stratigraphicUnit.code' => 'Stratigraphic Unit Code',
        'taxonomy.value' => 'Taxonomy',
        'taxonomy.flat.value' => 'Taxonomy Flat',
        'taxonomy.flat.level' => 'Taxonomy Flat Level',
        'taxonomy.flat.rank' => 'Taxonomy Flat Rank',
        'taxonomy.flat.species' => 'Taxonomy Flat Species',
        'taxonomy.flat.genus' => 'Taxonomy Flat Genus',
        'taxonomy.flat.family' => 'Taxonomy Flat Family',
        'taxonomy.flat.class' => 'Taxonomy Flat Class',
        'taxonomy.flat.spanishName' => 'Taxonomy Flat Spanish Name',
        'taxonomy.flat.englishName' => 'Taxonomy Flat English Name',
        'taxonomy.flat.genusId' => 'Taxonomy Flat Genus Id',
        'taxonomy.flat.familyId' => 'Taxonomy Flat Family Id',
        'taxonomy.flat.classId' => 'Taxonomy Flat Class Id',
        'element.value' => 'Element',
        'part.value' => 'Part',
        'cf' => 'Cf',
        'sp' => 'Sp',
        'type' => 'Type',
        'notes' => 'Notes',
    ],
    Context::class => [
        'id' => 'Id',
        'type' => 'Type',
        'site.code' => 'Site Code',
        'site.name' => 'Site Name',
        'name' => 'Name',
        'description' => 'Description',
        'code' => 'Code',
    ],
    Animal::class => [
        'id' => 'Id',
        'language.value' => 'Language',
        'animal' => 'Animal',
        'taxonomy.value' => 'Taxonomy',
        'taxonomy.englishName' => 'Taxonomy English Name',
        'taxonomy.spanishName' => 'Taxonomy Spanish Name',
        'taxonomy.class' => 'Taxonomy Class',
        'taxonomy.family' => 'Taxonomy Family',
        'location.value' => 'Location',
        'location.region.value' => 'Location Region',
        'location.n' => 'Location N',
        'location.e' => 'Location E',
        'chronologyLower' => 'Chronology Lower',
        'chronologyUpper' => 'Chronology Upper',
        'reference' => 'Reference',
        'notes' => 'Notes',
    ],
    Plant::class => [
        'id' => 'Id',
        'language.value' => 'Language',
        'plant' => 'Plant',
        'taxonomy.value' => 'Taxonomy',
        'taxonomy.flat.value' => 'Taxonomy Flat',
        'taxonomy.flat.level' => 'Taxonomy Flat Level',
        'taxonomy.flat.rank' => 'Taxonomy Flat Rank',
        'taxonomy.flat.species' => 'Taxonomy Flat Species',
        'taxonomy.flat.genus' => 'Taxonomy Flat Genus',
        'taxonomy.flat.family' => 'Taxonomy Flat Family',
        'taxonomy.flat.class' => 'Taxonomy Flat Class',
        'taxonomy.flat.spanishName' => 'Taxonomy Flat Spanish Name',
        'taxonomy.flat.englishName' => 'Taxonomy Flat English Name',
        'taxonomy.flat.genusId' => 'Taxonomy Flat Genus Id',
        'taxonomy.flat.familyId' => 'Taxonomy Flat Family Id',
        'taxonomy.flat.classId' => 'Taxonomy Flat Class Id',
        'cf' => 'Cf',
        'sp' => 'Sp',
        'location.value' => 'Location',
        'location.region.value' => 'Location Region',
        'location.n' => 'Location N',
        'location.e' => 'Location E',
        'chronologyLower' => 'Chronology Lower',
        'chronologyUpper' => 'Chronology Upper',
        'reference' => 'Reference',
        'notes' => 'Notes',
    ],
    WrittenSource::class => [
        'id' => 'Id',
        'writtenSourceType.value' => 'Written Source Type',
        'author.value' => 'Author',
        'author.variant' => 'Author Variant',
        'title' => 'Title',
        'subtitle' => 'Subtitle',
        'publicationDetails' => 'Publication Details',
        'notes' => 'Notes',
        'century' => 'Century',
        'region' => 'Region',
    ],
    WrittenSourceCitedWork::class => [
        'id' => 'Id',
        'writtenSource.writtenSourceType.value' => 'Written Source Written Source Type',
        'writtenSource.author.value' => 'Written Source Author',
        'writtenSource.author.variant' => 'Written Source Author Variant',
        'writtenSource.title' => 'Written Source Title',
        'writtenSource.subtitle' => 'Written Source Subtitle',
        'writtenSource.publicationDetails' => 'Written Source Publication Details',
        'writtenSource.notes' => 'Written Source Notes',
        'writtenSource.century' => 'Written Source Century',
        'writtenSource.region' => 'Written Source Region',
        'citedWork.value' => 'Cited Work',
        'yearCompletedRange' => 'Year Completed Range',
    ],
    Individual::class => [
        'id' => 'Id',
        'stratigraphicUnit.site.code' => 'Stratigraphic Unit Site Code',
        'stratigraphicUnit.site.name' => 'Stratigraphic Unit Site Name',
        'stratigraphicUnit.code' => 'Stratigraphic Unit Code',
        'identifier' => 'Identifier',
        'age.value' => 'Age',
        'sex.code' => 'Sex Code',
        'notes' => 'Notes',
        'code' => 'Code',
    ],
    AnalysisBotanyCharcoal::class => [
        'id' => 'Id',
        'subject.flat.value' => 'Subject',
        'subject.stratigraphicUnit.site.code' => 'Subject Stratigraphic Unit Site Code',
        'subject.stratigraphicUnit.site.name' => 'Subject Stratigraphic Unit Site Name',
        'subject.stratigraphicUnit.code' => 'Subject Stratigraphic Unit Code',
        'subject.taxonomy.value' => 'Subject Taxonomy',
        'subject.taxonomy.flat.value' => 'Subject Taxonomy Flat',
        'subject.taxonomy.flat.level' => 'Subject Taxonomy Flat Level',
        'subject.taxonomy.flat.rank' => 'Subject Taxonomy Flat Rank',
        'subject.taxonomy.flat.species' => 'Subject Taxonomy Flat Species',
        'subject.taxonomy.flat.genus' => 'Subject Taxonomy Flat Genus',
        'subject.taxonomy.flat.family' => 'Subject Taxonomy Flat Family',
        'subject.taxonomy.flat.class' => 'Subject Taxonomy Flat Class',
        'subject.taxonomy.flat.spanishName' => 'Subject Taxonomy Flat Spanish Name',
        'subject.taxonomy.flat.englishName' => 'Subject Taxonomy Flat English Name',
        'subject.taxonomy.flat.genusId' => 'Subject Taxonomy Flat Genus Id',
        'subject.taxonomy.flat.familyId' => 'Subject Taxonomy Flat Family Id',
        'subject.taxonomy.flat.classId' => 'Subject Taxonomy Flat Class Id',
        'subject.part.value' => 'Subject Part',
        'subject.cf' => 'Subject Cf',
        'subject.sp' => 'Subject Sp',
        'subject.type' => 'Subject Type',
        'subject.notes' => 'Subject Notes',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisBotanySeed::class => [
        'id' => 'Id',
        'subject.flat.value' => 'Subject',
        'subject.stratigraphicUnit.site.code' => 'Subject Stratigraphic Unit Site Code',
        'subject.stratigraphicUnit.site.name' => 'Subject Stratigraphic Unit Site Name',
        'subject.stratigraphicUnit.code' => 'Subject Stratigraphic Unit Code',
        'subject.taxonomy.value' => 'Subject Taxonomy',
        'subject.taxonomy.flat.value' => 'Subject Taxonomy Flat',
        'subject.taxonomy.flat.level' => 'Subject Taxonomy Flat Level',
        'subject.taxonomy.flat.rank' => 'Subject Taxonomy Flat Rank',
        'subject.taxonomy.flat.species' => 'Subject Taxonomy Flat Species',
        'subject.taxonomy.flat.genus' => 'Subject Taxonomy Flat Genus',
        'subject.taxonomy.flat.family' => 'Subject Taxonomy Flat Family',
        'subject.taxonomy.flat.class' => 'Subject Taxonomy Flat Class',
        'subject.taxonomy.flat.spanishName' => 'Subject Taxonomy Flat Spanish Name',
        'subject.taxonomy.flat.englishName' => 'Subject Taxonomy Flat English Name',
        'subject.taxonomy.flat.genusId' => 'Subject Taxonomy Flat Genus Id',
        'subject.taxonomy.flat.familyId' => 'Subject Taxonomy Flat Family Id',
        'subject.taxonomy.flat.classId' => 'Subject Taxonomy Flat Class Id',
        'subject.element.value' => 'Subject Element',
        'subject.part.value' => 'Subject Part',
        'subject.cf' => 'Subject Cf',
        'subject.sp' => 'Subject Sp',
        'subject.type' => 'Subject Type',
        'subject.notes' => 'Subject Notes',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisContextBotany::class => [
        'subject.id' => 'Subject Id',
        'subject.type' => 'Subject Type',
        'subject.site.code' => 'Subject Site Code',
        'subject.site.name' => 'Subject Site Name',
        'subject.name' => 'Subject Name',
        'subject.description' => 'Subject Description',
        'subject.code' => 'Subject Code',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisContextZoo::class => [
        'subject.id' => 'Subject Id',
        'subject.type' => 'Subject Type',
        'subject.site.code' => 'Subject Site Code',
        'subject.site.name' => 'Subject Site Name',
        'subject.name' => 'Subject Name',
        'subject.description' => 'Subject Description',
        'subject.code' => 'Subject Code',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisIndividual::class => [
        'subject.id' => 'Subject Id',
        'subject.stratigraphicUnit.site.code' => 'Subject Stratigraphic Unit Site Code',
        'subject.stratigraphicUnit.site.name' => 'Subject Stratigraphic Unit Site Name',
        'subject.stratigraphicUnit.code' => 'Subject Stratigraphic Unit Code',
        'subject.identifier' => 'Subject Identifier',
        'subject.age.value' => 'Subject Age',
        'subject.sex.code' => 'Subject Sex Code',
        'subject.notes' => 'Subject Notes',
        'subject.code' => 'Subject Code',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisPottery::class => [
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisSample::class => [
        'id' => 'Id',
        'subject.id' => 'Subject Id',
        'subject.site.code' => 'Subject Site Code',
        'subject.site.name' => 'Subject Site Name',
        'subject.type.code' => 'Subject Type Code',
        'subject.type.value' => 'Subject Type',
        'subject.year' => 'Subject Year',
        'subject.number' => 'Subject Number',
        'subject.description' => 'Subject Description',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisSampleBotany::class => [
        'subject.id' => 'Subject Id',
        'subject.site.code' => 'Subject Site Code',
        'subject.site.name' => 'Subject Site Name',
        'subject.type.code' => 'Subject Type Code',
        'subject.type.value' => 'Subject Type',
        'subject.year' => 'Subject Year',
        'subject.number' => 'Subject Number',
        'subject.description' => 'Subject Description',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisSampleMicrostratigraphy::class => [
        'id' => 'Id',
        'subject.id' => 'Subject Id',
        'subject.site.code' => 'Subject Site Code',
        'subject.site.name' => 'Subject Site Name',
        'subject.type.code' => 'Subject Type Code',
        'subject.type.value' => 'Subject Type',
        'subject.year' => 'Subject Year',
        'subject.number' => 'Subject Number',
        'subject.description' => 'Subject Description',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisSedimentCoreDepth::class => [
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisSedimentCoreDepthBotany::class => [
        'id' => 'Id',
        'subject.geochemistry' => 'Subject Geochemistry',
        'subject.microCharcoal' => 'Subject Micro Charcoal',
        'subject.organicChemistry' => 'Subject Organic Chemistry',
        'subject.oslDating' => 'Subject Osl Dating',
        'subject.phytoliths' => 'Subject Phytoliths',
        'subject.plantMacroRemains' => 'Subject Plant Macro Remains',
        'subject.pollen' => 'Subject Pollen',
        'subject.sedimentaryDna' => 'Subject Sedimentary Dna',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisSiteAnthropology::class => [
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisZooBone::class => [
        'id' => 'Id',
        'subject.stratigraphicUnit.site.code' => 'Subject Stratigraphic Unit Site Code',
        'subject.stratigraphicUnit.site.name' => 'Subject Stratigraphic Unit Site Name',
        'subject.stratigraphicUnit.code' => 'Subject Stratigraphic Unit Code',
        'subject.taxonomy.code' => 'Subject Taxonomy Code',
        'subject.taxonomy.value' => 'Subject Taxonomy',
        'subject.taxonomy.englishName' => 'Subject Taxonomy English Name',
        'subject.taxonomy.spanishName' => 'Subject Taxonomy Spanish Name',
        'subject.taxonomy.class' => 'Subject Taxonomy Class',
        'subject.taxonomy.family' => 'Subject Taxonomy Family',
        'subject.element.code' => 'Subject Element Code',
        'subject.element.value' => 'Subject Element',
        'subject.part.code' => 'Subject Part Code',
        'subject.part.value' => 'Subject Part',
        'subject.endsPreserved.code' => 'Subject Ends Preserved Code',
        'subject.endsPreserved.value' => 'Subject Ends Preserved',
        'subject.notes' => 'Subject Notes',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    AnalysisZooTooth::class => [
        'id' => 'Id',
        'analysis.id' => 'Analysis Id',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.code' => 'Analysis Type Code',
        'analysis.type.group' => 'Analysis Type Group',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.summary' => 'Analysis Summary',
        'analysis.code' => 'Analysis Code',
        'summary' => 'Summary',
    ],
    ContextStratigraphicUnit::class => [
        'context.id' => 'Context Id',
        'context.type' => 'Context Type',
        'context.site.code' => 'Context Site Code',
        'context.site.name' => 'Context Site Name',
        'context.name' => 'Context Name',
        'context.description' => 'Context Description',
        'context.code' => 'Context Code',
    ],
    SampleStratigraphicUnit::class => [
        'sample.id' => 'Sample Id',
        'sample.site.code' => 'Sample Site Code',
        'sample.site.name' => 'Sample Site Name',
        'sample.type.code' => 'Sample Type Code',
        'sample.type.value' => 'Sample Type',
        'sample.year' => 'Sample Year',
        'sample.number' => 'Sample Number',
        'sample.description' => 'Sample Description',
    ],
    SedimentCoreDepth::class => [
        'geochemistry' => 'Geochemistry',
        'microCharcoal' => 'Micro Charcoal',
        'organicChemistry' => 'Organic Chemistry',
        'oslDating' => 'Osl Dating',
        'phytoliths' => 'Phytoliths',
        'plantMacroRemains' => 'Plant Macro Remains',
        'pollen' => 'Pollen',
        'sedimentaryDna' => 'Sedimentary Dna',
    ],
    MicrostratigraphicUnit::class => [
        'id' => 'Id',
        'stratigraphicUnit.site.code' => 'Stratigraphic Unit Site Code',
        'stratigraphicUnit.site.name' => 'Stratigraphic Unit Site Name',
        'stratigraphicUnit.code' => 'Stratigraphic Unit Code',
        'identifier' => 'Identifier',
        'notes' => 'Notes',
        'code' => 'Code',
    ],
    PaleoclimateSample::class => [
        'id' => 'Id',
        'site.code' => 'Site Code',
        'site.name' => 'Site Name',
        'number' => 'Number',
        'description' => 'Description',
        'chronologyLower' => 'Chronology Lower',
        'chronologyUpper' => 'Chronology Upper',
        'length' => 'Length',
        'temperatureRecord' => 'Temperature Record',
        'precipitationRecord' => 'Precipitation Record',
        'stableIsotopes' => 'Stable Isotopes',
        'traceElements' => 'Trace Elements',
        'petrographicDescriptions' => 'Petrographic Descriptions',
        'fluidInclusions' => 'Fluid Inclusions',
        'code' => 'Code',
    ],
    PaleoclimateSamplingSite::class => [
        'id' => 'Id',
        'code' => 'Code',
        'name' => 'Name',
        'description' => 'Description',
        'region.value' => 'Region',
    ],
    Pottery::class => [
        'id' => 'Id',
        'stratigraphicUnit.site.code' => 'Stratigraphic Unit Site Code',
        'stratigraphicUnit.site.name' => 'Stratigraphic Unit Site Name',
        'stratigraphicUnit.code' => 'Stratigraphic Unit Code',
        'inventory' => 'Inventory',
        'surfaceTreatment.value' => 'Surface Treatment',
        'surfaceTreatment.variant' => 'Surface Treatment Variant',
        'innerColor' => 'Inner Color',
        'outerColor' => 'Outer Color',
        'decorationMotif' => 'Decoration Motif',
        'culturalContext.value' => 'Cultural Context',
        'chronologyLower' => 'Chronology Lower',
        'chronologyUpper' => 'Chronology Upper',
        'shape.value' => 'Shape',
        'shape.variant' => 'Shape Variant',
        'functionalForm.value' => 'Functional Form',
        'functionalForm.variant' => 'Functional Form Variant',
        'functionalForm.functionalGroup.value' => 'Functional Form Functional Group',
        'notes' => 'Notes',
    ],
    Sample::class => [
        'id' => 'Id',
        'site.code' => 'Site Code',
        'site.name' => 'Site Name',
        'type.code' => 'Type Code',
        'type.value' => 'Type',
        'year' => 'Year',
        'number' => 'Number',
        'description' => 'Description',
    ],
    SamplingSite::class => [
        'id' => 'Id',
        'code' => 'Code',
        'name' => 'Name',
        'description' => 'Description',
        'region.value' => 'Region',
    ],
    SamplingStratigraphicUnit::class => [
        'id' => 'Id',
        'site.code' => 'Site Code',
        'site.name' => 'Site Name',
        'number' => 'Number',
        'description' => 'Description',
        'interpretation' => 'Interpretation',
        'chronologyLower' => 'Chronology Lower',
        'chronologyUpper' => 'Chronology Upper',
        'code' => 'Code',
    ],
    SedimentCore::class => [
        'id' => 'Id',
        'year' => 'Year',
        'number' => 'Number',
        'description' => 'Description',
    ],
    StratigraphicUnit::class => [
        'id' => 'Id',
        'site.id' => 'Site Id',
        'site.code' => 'Site Code',
        'site.name' => 'Site Name',
        'area' => 'Area',
        'building' => 'Building',
        'year' => 'Year',
        'number' => 'Number',
        'description' => 'Description',
        'interpretation' => 'Interpretation',
        'chronologyLower' => 'Chronology Lower',
        'chronologyUpper' => 'Chronology Upper',
    ],
    AbsDatingAnalysisView::class => [
        'id' => 'Id',
        'stratigraphicUnit.site.code' => 'Stratigraphic Unit Site Code',
        'stratigraphicUnit.site.name' => 'Stratigraphic Unit Site Name',
        'stratigraphicUnit.code' => 'Stratigraphic Unit Code',
        'analysis.identifier' => 'Analysis Identifier',
        'analysis.status' => 'Analysis Status',
        'analysis.type.value' => 'Analysis Type',
        'analysis.responsible' => 'Analysis Responsible',
        'analysis.year' => 'Analysis Year',
        'analysis.laboratory' => 'Analysis Laboratory',
        'analysis.code' => 'Analysis Code',
        'subjectId' => 'Subject Id',
        'subjectType' => 'Subject Type',
        'resourceLabel' => 'Resource Label',
        'datingLower' => 'Dating Lower',
        'datingUpper' => 'Dating Upper',
        'uncalibratedDating' => 'Uncalibrated Dating',
        'error' => 'Error',
        'calibrationCurve' => 'Calibration Curve',
        'probability' => 'Probability',
        'notes' => 'Notes',
    ],
    Bone::class => [
        'stratigraphicUnit.site.code' => 'Stratigraphic Unit Site Code',
        'stratigraphicUnit.site.name' => 'Stratigraphic Unit Site Name',
        'stratigraphicUnit.code' => 'Stratigraphic Unit Code',
        'taxonomy.code' => 'Taxonomy Code',
        'taxonomy.value' => 'Taxonomy',
        'taxonomy.englishName' => 'Taxonomy English Name',
        'taxonomy.spanishName' => 'Taxonomy Spanish Name',
        'taxonomy.class' => 'Taxonomy Class',
        'taxonomy.family' => 'Taxonomy Family',
        'element.code' => 'Element Code',
        'element.value' => 'Element',
        'part.code' => 'Part Code',
        'part.value' => 'Part',
        'endsPreserved.code' => 'Ends Preserved Code',
        'endsPreserved.value' => 'Ends Preserved',
        'notes' => 'Notes',
    ],
    Tooth::class => [
        'stratigraphicUnit.site.code' => 'Stratigraphic Unit Site Code',
        'stratigraphicUnit.site.name' => 'Stratigraphic Unit Site Name',
        'stratigraphicUnit.code' => 'Stratigraphic Unit Code',
        'taxonomy.code' => 'Taxonomy Code',
        'taxonomy.value' => 'Taxonomy',
        'taxonomy.englishName' => 'Taxonomy English Name',
        'taxonomy.spanishName' => 'Taxonomy Spanish Name',
        'taxonomy.class' => 'Taxonomy Class',
        'taxonomy.family' => 'Taxonomy Family',
        'element.code' => 'Element Code',
        'element.value' => 'Element',
        'connected' => 'Connected',
        'notes' => 'Notes',
    ],
];
