<?php

namespace App\Metadata\Attribute;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Link;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;

/**
 * Custom API Platform resource attribute for Analysis Botany Taxonomy join entities.
 *
 * This attribute automatically configures CRUD operations for botany taxonomy associations.
 * Note: All routes generated by this attribute are prefixed with `/data` via the `routePrefix` parameter.
 *
 * @see ApiResource
 */
#[\Attribute(\Attribute::TARGET_CLASS)]
class ApiAnalysisBotanyTaxonomyResource extends ApiResource
{
    public function __construct(
        string $taxonomyResourceName,
        string $readGroup,
        string $createGroup,
        string $updateGroup,
        string $parentResourceName,
        string $parentClass,
    ) {
        parent::__construct(
            operations: [
                new Get(
                    uriTemplate: "/analyses/$taxonomyResourceName/{id}",
                    requirements: ['id' => '\d+'],
                ),
                new GetCollection(
                    uriTemplate: "/analyses/$taxonomyResourceName",
                    //                    order: ['id' => 'DESC'],
                ),
                new GetCollection(
                    uriTemplate: "/analyses/$parentResourceName/{parentId}/taxonomies",
                    uriVariables: [
                        'parentId' => new Link(
                            fromProperty: 'taxonomies',
                            fromClass: $parentClass,
                        ),
                    ],
                    //                    order: ['id' => 'DESC'],
                ),
                new Post(
                    uriTemplate: "/analyses/$taxonomyResourceName",
                    denormalizationContext: [
                        'groups' => [$createGroup],
                    ],
                    securityPostDenormalize: "is_granted('create', object)",
                ),
                new Patch(
                    uriTemplate: "/analyses/$taxonomyResourceName/{id}",
                    requirements: ['id' => '\d+'],
                    denormalizationContext: [
                        'groups' => [$updateGroup],
                    ],
                    security: "is_granted('update', object)",
                ),
                new Delete(
                    uriTemplate: "/analyses/$taxonomyResourceName/{id}",
                    requirements: ['id' => '\d+'],
                    security: "is_granted('delete', object)",
                    output: false,
                ),
            ],
            routePrefix: 'data',
            normalizationContext: [
                'groups' => [$readGroup, 'analysis_join:acl:read'],
            ],
            order: ['id' => 'DESC'],
        );
    }
}
